### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by exotropos** [MiraBellierr/client-bot#1]
Are you able to code it so people can report others? And the reports can go to a hidden report channel only I can see

**Comment by MiraBellierr** [comment]
The report command has been added. If you found bugs or want to request the changes to this command, feel free to open an issue.

To set it up:

- Do `report set <channel ID>`.

To report:

- Do `report <member ID | username | nickname | mention> <report content>`.
You can include the image when reporting the member.
